apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-ingress-conf
  namespace: apisix
data:
  config.yaml: |
    apisix:
      base_url: "http://apisix-admin.apisix.svc.cluster.local:9180/apisix/admin""
      admin_key: "edd1c9f034335f136f87ad84b625c8f1"
