apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-conf
  namespace: apisix
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_admin: true
      admin_key:
        - name: "admin"
          key: edd1c9f034335f136f87ad84b625c88b
          role: admin
    deployment:
      role: traditional
      role_apisix_control_plane:
        config_provider: etcd
        etcd:
          host:
            - "http://etcd:2379" # Aquí es donde está tu StatefulSet
          prefix: "/apisix"
